### ISSUE TITLE
SIMPLIFY - extra code

### ISSUE THREAD

**Issue by franfranfranfran** [johnyboy21/tea_cozy#1]
watch out for extra, unused code. make sure each line you add serves some purpose on the page and strive to avoid repeating lines of styling wherever possible.

couple examples -

https://github.com/johnyboy21/tea_cozy/blob/master/resources/css/style.css#L80
no need to set width to 1200px for locations because locations is inside of main-content and that already has a 1200px fixed width.

https://github.com/johnyboy21/tea_cozy/blob/master/resources/css/style.css#L19-L23
head could easily be replaced with the container class so that you could get rid of this extra styling that appears to be the same for both.

**Comment by johnyboy21** [comment]
Thanks for the help!  I'll make sure to keep an eye out for that on my next project.
