### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [johnyboy21/tea_cozy#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Good work on this project. The site looks great and you did an excellent job keeping both the project folder and the code itself neat, organized, and readable. Good use of flex display to help align items throughout the page as well!

I don't have much in the way of issues for this particular project, but there are a couple small areas you could examine. Consider using some comments to help organize your css further, this will help make changes / updates later on a bit easier. Also, keep an eye out for extra, unused code as you build your projects. Make sure each line you add serves some purpose on the page. 

From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Have fun and keep up the good work!

**Comment by johnyboy21** [comment]
Thanks again for the review!  I'm really excited about everything I've learned so far in this course and look forward to making the suggested changes on my future projects.  

Slow and steady but still having fun!
